
# ============================================================
# QSP CIRCUIT ON BELENOS QPU -- UNITARY EMBEDDING INVESTIGATION
# ============================================================
#
# GOAL:
#   Investigate how our 2-mode QSP circuit (which produces a
#   2x2 unitary) is mapped onto the Belenos chip which has
#   24 modes and requires a 24x24 unitary transformation.
#
# BACKGROUND:
#   Our QSP circuit for L layers uses (L+1) Ry(theta) gates
#   and phase shifters, all acting on only 2 modes. This always
#   produces a 2x2 SU(2) unitary W = [[P, -Q*], [Q, P*]].
#   But Belenos is a 24-mode universal chip with fixed 50:50
#   BSs and 552 tunable PSs. So how does the 2x2 unitary get
#   mapped onto the full 24-mode chip?
#
# WHAT THIS CODE DOES (step by step):
#
#   Step 0: Define build_qsp_pic() -- builds the 2-mode QSP
#           circuit from loaded angles for a given L and x.
#
#   Step 1: Load QSP angles for L=2 from .npy files generated
#           by qsp_pq_angle_generator.py
#
#   Step 2: Build the circuit and extract the exact 2x2 unitary
#           using Perceval's compute_unitary().
#
#   Step 3: Manually embed the 2x2 unitary into a 24x24 identity
#           matrix (U_24 = U_2x2 ⊕ I_22) as a reference.
#           NOTE: this is just for comparison -- we later found
#           that Belenos does NOT use this simple embedding.
#
#   Step 4: Connect to the Belenos QPU via Quandela Cloud using
#           the API token and set our 2-mode circuit.
#
#   Step 5: Inspect the transpiled circuit returned by Perceval.
#           At this stage, all PS values are None -- they are
#           filled in on the cloud at job submission time.
#
#   Step 6: Print the full Belenos chip specs, including the
#           number of modes (24), available commands, and
#           hardware constraints (max photons, detector type).
#
#   Step 7: Extract the architecture object from the chip specs
#           to inspect the full 24-mode chip structure.
#
#   Step 8: Print all 552 PS parameter slots across the full
#           Belenos chip. All values are None locally -- they
#           are filled by universalchipworker on the cloud.
#
#   Step 9: Submit a real job to Belenos QPU with 100 shots.
#           Input state: |1,0> (photon in mode 0).
#           This consumes QPU credits.
#
#   Step 10: Wait for the job to complete (polls every 5 sec).
#
#   Step 11: Inspect the computed_circuit returned in results.
#            This is the actual 24x24 circuit that ran on the
#            chip, with all 552 PS values filled in.
#            Key checks:
#              - Is the circuit 24 modes? (yes, confirmed)
#              - Does the top-left 2x2 match our QSP unitary?
#                (NO -- it does not match, proving that Belenos
#                does NOT use a simple block-diagonal embedding)
#
# KEY FINDING FROM THIS CODE:
#   The top-left 2x2 block of the 24x24 Belenos unitary does
#   NOT match our original 2x2 QSP unitary. This means the
#   compiler (universalchipworker) does NOT simply embed the
#   2x2 into a block-diagonal 24x24 matrix. Instead it finds
#   a full 24x24 unitary through optimization (CircuitOptimizer)
#   that correctly implements our 2-mode operation.
#   This question was sent to Samuel at Quandela for clarification.
#
# OPEN QUESTION (pending Samuel's reply):
#   Does universalchipworker first embed U_2x2 into a 24x24
#   block-diagonal matrix and then optimize the PS values?
#   Or does it optimize directly from the 2-mode circuit
#   description without an explicit embedding step?
#
# FILE NAMING:
#   Angle files: theta_step_pq_L2.npy, phi_step_pq_L2.npy
#   Generated by: qsp_pq_angle_generator.py
#
# NOTE ON QPU CREDITS:
#   Step 9 submits a real job and consumes Quandela Cloud credits.
#   Reduce N_shots or comment out Steps 9-11 to avoid credit use.
# ============================================================

import numpy as np
import perceval as pcvl
import perceval.components as comp
from perceval.algorithm import Sampler
import json
import time

# ── Step 0: Define build_qsp_pic ──────────────────────────
FUNC_NAME = "STEP"

def build_qsp_pic(theta_arr, phi_arr, x_val, L):
    circuit = pcvl.Circuit(2, name=f"QSP_{FUNC_NAME}_L{L}")
    circuit.add(0,      comp.PS(float(-phi_arr[0] / 2)))
    circuit.add(1,      comp.PS(float( phi_arr[0] / 2)))
    circuit.add((0, 1), comp.BS.Ry(theta=float(theta_arr[0])))
    for j in range(1, L + 1):
        circuit.add(0, comp.PS(float(-x_val / 2)))
        circuit.add(1, comp.PS(float( x_val / 2)))
        circuit.add(0,      comp.PS(float(-phi_arr[j] / 2)))
        circuit.add(1,      comp.PS(float( phi_arr[j] / 2)))
        circuit.add((0, 1), comp.BS.Ry(theta=float(theta_arr[j])))
    return circuit

# ── Step 1: Load angles for L=2 ───────────────────────────
theta_arr = np.load("theta_step_pq_L2.npy")
phi_arr   = np.load("phi_step_pq_L2.npy")
L     = 2
x_val = 0.5
assert len(theta_arr) - 1 == L
print(f"Angles loaded successfully: L={L}, x={x_val}")

# ── Step 2: Build circuit and get 2x2 unitary ─────────────
circuit_2mode = build_qsp_pic(theta_arr, phi_arr, x_val, L)
U_2x2 = np.array(circuit_2mode.compute_unitary())
print("\n=== Original 2x2 QSP Unitary (L=2, x=0.5) ===")
print(np.round(U_2x2, 4))
print(f"Is unitary: {np.allclose(U_2x2 @ U_2x2.conj().T, np.eye(2), atol=1e-6)}")

# ── Step 3: Manual 24x24 embedding (for reference only) ───
U_24x24 = np.eye(24, dtype=complex)
U_24x24[0:2, 0:2] = U_2x2
print("\n=== Manual 24x24 Embedding (top-left 4x4 shown) ===")
print(np.round(U_24x24[:4, :4], 4))

# ── Step 4: Connect to Belenos ────────────────────────────
TOKEN = "_T_eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjU5MiwiZXhwIjoxODA2NTkwNjc1LjE4NjQ3NDN9.eCJCJNcF7BqyUtKiUSaOPK1RM0Nd42B-2UXwH0IIRiYy0TOqi9eQWcUM3049KIkcjgyKkHT-xyIxzoqzmuxyaQ"
provider = pcvl.RemoteProcessor("qpu:belenos", token=TOKEN)
provider.set_circuit(circuit_2mode)

# ── Step 5: Inspect transpiled circuit (params will be None)
transpiled = provider.linear_circuit()
print(f"\n=== Transpiled circuit type: {type(transpiled)} ===")
print("\n=== All PS values (expect None -- filled on cloud) ===")
for i, (modes, component) in enumerate(transpiled):
    print(f"  component {i:3d}  modes={modes}  params={component.get_parameters()}")

# ── Step 6: Chip specs ────────────────────────────────────
print("\n=== Belenos chip specs ===")
print(provider.specs)
print("\n=== Available commands ===")
print(provider.available_commands)

# ── Step 7: Architecture object ───────────────────────────
arch = provider.specs['architecture']
print(f"\nArchitecture type: {type(arch)}")
print(f"Architecture attributes:")
print([x for x in dir(arch) if not x.startswith('_')])

# ── Step 8: Full chip circuit ─────────────────────────────
full_circuit = arch.unitary_circuit()
print(f"\n=== Full Belenos circuit size: {arch.m} modes ===")
print("\n=== All component PS values across full chip ===")
for i, (modes, component) in enumerate(arch.components):
    print(f"  component {i:3d}  modes={modes}  params={component.get_parameters()}")

# ── Step 9: Submit job ────────────────────────────────────
provider2 = pcvl.RemoteProcessor("qpu:belenos", token=TOKEN)
provider2.set_circuit(circuit_2mode)
provider2.with_input(pcvl.BasicState([1, 0]))
provider2.min_detected_photons_filter(1)

sampler2 = Sampler(provider2, max_shots_per_call=100)
job = sampler2.sample_count.execute_async(100)

print("\n=== Job ID ===")
print(job.id)

# ── Step 10: Wait for completion ──────────────────────────
print("\nWaiting for job to complete...")
while not job.is_complete:
    print(f"  Status: {job.status}...")
    time.sleep(5)

results = job.get_results()
print("\n=== Raw results ===")
print(results)
print("\n=== All result keys ===")
print(list(results.keys()))

# ── Step 11: Inspect computed_circuit ─────────────────────
cc = results['computed_circuit']
print(f"\n=== computed_circuit size: {cc.m} modes ===")

print("\n=== All components in computed_circuit ===")
for i, (modes, component) in enumerate(cc):
    params = component.get_parameters()
    print(f"  component {i:3d}  modes={modes}  params={params}")

print("\n=== computed_circuit unitary ===")
try:
    U_cc = np.array(cc.compute_unitary())
    print(f"Shape: {U_cc.shape}")
    print(f"\nFull unitary:\n{np.round(U_cc, 4)}")
    print(f"\n=== Top-left 2x2 of computed_circuit ===")
    print(np.round(U_cc[:2, :2], 4))
    print(f"\n=== Your original 2x2 QSP unitary ===")
    print(np.round(U_2x2, 4))
    print(f"\nDo they match? {np.allclose(U_cc[:2,:2], U_2x2, atol=1e-3)}")
except Exception as e:
    print(f"compute_unitary failed: {e}")