# ============================================================
# QSP UNITARY DECOMPOSITION INTO MZI CIRCUIT
# ============================================================
#
# GOAL:
#   Take the 2x2 unitary produced by our QSP circuit (for a
#   given L and x value) and decompose it into a physical
#   photonic circuit made of MZIs (Mach-Zehnder Interferometers)
#   using a custom MZI building block: BS + PS + BS + PS.
#
# DIFFERENCE FROM ReckDecomposition_U2_BSTheta.py:
#   That script uses a single BS with two parameters (theta, phi_tr)
#   as the building block -- simpler, fewer components.
#   This script uses a full MZI (BS + PS + BS + PS) as the
#   building block -- more physically realistic, matches the
#   actual MZI structure used in photonic chips like Belenos.
#
# KEY FINDING:
#   No matter what L is (2, 3, 10, 360...), the QSP circuit
#   always produces a 2x2 SU(2) unitary of the form:
#       W = [[P, -Q*], [Q, P*]]
#   This structure always decomposes into exactly:
#       2 BSs + 4 PSs  (i.e. 2 MZIs)
#   regardless of L. L only affects the polynomial
#   approximation quality, not the circuit structure.
#
# WHY pcvl.random_seed(42):
#   pcvl.Circuit.decomposition() uses a HYBRID approach:
#     - Circuit STRUCTURE (how many BSs/PSs) : analytical
#     - Actual ANGLE VALUES (theta, phi)     : numerical search
#       starting from a RANDOM initial point
#   Without fixing the seed, each run starts from a different
#   random point and finds a different set of valid angles --
#   all correct, but the circuit diagram looks different each
#   time. Setting pcvl.random_seed(42) forces the same starting
#   point every run, giving identical reproducible results.
#   The number 42 is arbitrary -- any fixed integer works.
#
# HOW TO USE:
#   Change L to any value you have angle files for.
#   Make sure theta_step_pq_L{L}.npy and phi_step_pq_L{L}.npy
#   exist in the working directory.
#
# FILE NAMING:
#   Angle files: theta_step_pq_L{L}.npy, phi_step_pq_L{L}.npy
#   Generated by: qsp_pq_angle_generator.py
# ============================================================
import numpy as np
import perceval as pcvl
import perceval.components as comp
from perceval.components import BS, PS

# ── Reproducibility fix ───────────────────────────────────
# pcvl.Circuit.decomposition() uses numerical search from a
# random starting point to find BS/PS angles. Without this
# seed, angle values differ every run. Setting the seed
# ensures identical reproducible results each run.
pcvl.random_seed(42)
FUNC_NAME = "STEP"

def build_qsp_pic(theta_arr, phi_arr, x_val, L):
    circuit = pcvl.Circuit(2, name=f"QSP_{FUNC_NAME}_L{L}")
    circuit.add(0,      comp.PS(float(-phi_arr[0] / 2)))
    circuit.add(1,      comp.PS(float( phi_arr[0] / 2)))
    circuit.add((0, 1), comp.BS.Ry(theta=float(theta_arr[0])))
    for j in range(1, L + 1):
        circuit.add(0, comp.PS(float(-x_val / 2)))
        circuit.add(1, comp.PS(float( x_val / 2)))
        circuit.add(0,      comp.PS(float(-phi_arr[j] / 2)))
        circuit.add(1,      comp.PS(float( phi_arr[j] / 2)))
        circuit.add((0, 1), comp.BS.Ry(theta=float(theta_arr[j])))
    return circuit

# ── Change L here ─────────────────────────────────────────
L     = 1     # <-- try 3, then 10
x_val = 0.5

theta_arr = np.load(f"theta_step_pq_L{L}.npy")
phi_arr   = np.load(f"phi_step_pq_L{L}.npy")

circuit_2mode = build_qsp_pic(theta_arr, phi_arr, x_val, L)
U = pcvl.Matrix(np.array(circuit_2mode.compute_unitary()).tolist())

print(f"=== QSP Unitary L={L}, x={x_val} ===")
print(np.round(np.array(U), 4))

# ── Decompose into MZIs ───────────────────────────────────
mzi = pcvl.Circuit(2) // BS() // (1, PS(pcvl.P("phi1"))) // BS() // (1, PS(pcvl.P("phi2")))
circuit_u = pcvl.Circuit.decomposition(U, mzi, phase_shifter_fn=PS)

# ── Display ───────────────────────────────────────────────
pcvl.pdisplay(circuit_u)

# ── Error check ───────────────────────────────────────────
error = np.linalg.norm(np.array(U) - np.array(circuit_u.compute_unitary()))
print(f"\nError between unitaries: {error:.2e}  (should be ~0)")

# ── Count components ──────────────────────────────────────
n_bs = sum(1 for modes, c in circuit_u if len(modes) == 2)
n_ps = sum(1 for modes, c in circuit_u if len(modes) == 1)
print(f"BSs: {n_bs}   PSs: {n_ps}")