# ============================================================
# QSP UNITARY DECOMPOSITION INTO BS + PS CIRCUIT
# ============================================================
#
# GOAL:
#   Take the 2x2 unitary produced by our QSP circuit (for a
#   given L and x value) and decompose it into a physical
#   photonic circuit made of Beam Splitters (BSs) and Phase
#   Shifters (PSs) using Perceval's Circuit.decomposition().
#
# KEY FINDING:
#   No matter what L is (2, 3, 10, 360...), the QSP circuit
#   always produces a 2x2 SU(2) unitary of the form:
#       W = [[P, -Q*], [Q, P*]]
#   This structure always decomposes into exactly:
#       1 BS + 2 PSs
#   regardless of L. L only affects the polynomial
#   approximation quality, not the circuit structure.
#
# WHY pcvl.random_seed(42):
#   pcvl.Circuit.decomposition() uses a HYBRID approach:
#     - Circuit STRUCTURE (how many BSs/PSs) : analytical
#     - Actual ANGLE VALUES (theta, phi)     : numerical search
#       starting from a RANDOM initial point
#   Without fixing the seed, each run starts from a different
#   random point and finds a different set of valid angles --
#   all correct, but the circuit diagram looks different each
#   time. Setting pcvl.random_seed(42) forces the same starting
#   point every run, giving identical reproducible results.
#   The number 42 is arbitrary -- any fixed integer works.
#
# HOW TO USE:
#   Change L to any value you have angle files for.
#   Make sure theta_step_pq_L{L}.npy and phi_step_pq_L{L}.npy
#   exist in the working directory.
#
# FILE NAMING:
#   Angle files: theta_step_pq_L{L}.npy, phi_step_pq_L{L}.npy
#   Generated by: qsp_pq_angle_generator.py
# ============================================================
import numpy as np
import perceval as pcvl
import perceval.components as comp
from perceval.components import BS, PS

# ── Fix: set Perceval random seed ────────────────────────
pcvl.random_seed(42)   # <-- add this as the FIRST line after imports
FUNC_NAME = "STEP"

def build_qsp_pic(theta_arr, phi_arr, x_val, L):
    circuit = pcvl.Circuit(2, name=f"QSP_{FUNC_NAME}_L{L}")
    circuit.add(0,      comp.PS(float(-phi_arr[0] / 2)))
    circuit.add(1,      comp.PS(float( phi_arr[0] / 2)))
    circuit.add((0, 1), comp.BS.Ry(theta=float(theta_arr[0])))
    for j in range(1, L + 1):
        circuit.add(0, comp.PS(float(-x_val / 2)))
        circuit.add(1, comp.PS(float( x_val / 2)))
        circuit.add(0,      comp.PS(float(-phi_arr[j] / 2)))
        circuit.add(1,      comp.PS(float( phi_arr[j] / 2)))
        circuit.add((0, 1), comp.BS.Ry(theta=float(theta_arr[j])))
    return circuit

x_val = 0.5

# ── Change L here ─────────────────────────────────────────
L = 360   # <-- change to 2, 10, 360, etc.

theta_arr = np.load(f"theta_step_pq_L{L}.npy")
phi_arr   = np.load(f"phi_step_pq_L{L}.npy")

# Get exact 2x2 unitary
circuit_2mode = build_qsp_pic(theta_arr, phi_arr, x_val, L)
U = pcvl.Matrix(np.array(circuit_2mode.compute_unitary()).tolist())

print(f"\n=== QSP Unitary L={L}, x={x_val} ===")
print(np.round(np.array(U), 4))

# Decompose
decomposed_circuit = pcvl.Circuit.decomposition(
    U,
    BS(theta=pcvl.P('theta'), phi_tr=pcvl.P('phi')),
    phase_shifter_fn=PS,
    shape="triangle"   # <-- add this explicitly
)

# Count components
n_bs = sum(1 for modes, c in decomposed_circuit if len(modes) == 2)
n_ps = sum(1 for modes, c in decomposed_circuit if len(modes) == 1)

print(f"\n=== Decomposed Circuit L={L} ===")
print(f"  BSs: {n_bs}   PSs: {n_ps}")

# Display circuit
pcvl.pdisplay(decomposed_circuit)

# Error check
error = np.linalg.norm(np.array(U) - np.array(decomposed_circuit.compute_unitary()))
print(f"\nError: {error:.2e}  (should be ~0)")